apiVersion: v1
kind: Service
metadata:
  name: springcloud-kubernetes-discovery-demo
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31080
      port: 8080
      targetPort: 8080
    - name: management
      nodePort: 31081
      port: 8081
      targetPort: 8081
  selector:
    app: springcloud-kubernetes-discovery-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcloud-kubernetes-discovery-demo
  labels:
    app: springcloud-kubernetes-discovery-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springcloud-kubernetes-discovery-demo
  template:
    metadata:
      name: springcloud-kubernetes-discovery-demo
      labels:
        app: springcloud-kubernetes-discovery-demo
    spec:
      serviceAccountName: springcloud-kubernetes
      restartPolicy: Always
      containers:
        - name: springcloud-k8s-config
          image: registry.cn-beijing.aliyuncs.com/mydlq/springcloud-kubernetes-discovery-demo:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m