apiVersion: v1
kind: ServiceAccount
metadata:
  name: springcloud-kubernetes
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: springcloud-kubernetes
subjects:
  - kind: ServiceAccount
    name: springcloud-kubernetes
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io